# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3915d3cc654087dc7d46af218adf5fa6378b9a6abbebbe9962235f72fc2abf791a402c86dc159fcd2b4e9953495e64fae94b8e1de9923032fedb6c1c1a32e007

test:
  secret_key_base: a2b7609db237c9149d3eb8750c4820a7c8e3a8f1b4fb223b2b1129a0544db9eb130113a6893506a69d5a43939c3eb7213cb0ef79278b940bac39f93b7f5f4b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
